mapping = {
    "id": "ID",
    "date": "Datum",
    "time": "Uhrzeit",
    "place": "Ort",
    "species": "Art",
    "count": "Anzahl",
    "melded": "Gemeldet",
    "excel_id": "Excel-ID",
    "ring": "Ring",
    "reading": "Ablesung",
    "area": "Bereich",
    "sex": "Geschlecht",
    "age": "Alter",
    "breed_size": "Brutgröße",
    "family_size": "Familiengröße",
    "pair": "Paar/Familie",
    "small_group_size": "Kleingruppengröße",
    "large_group_size": "Großgruppengröße",
    "partner": "Partner-Ring",
    "status": "Status",
    "habitat": "Habitat",
    "field_fruit": "Feldfrucht",
    "comment": "Kommentar",
    "melder": "Melder",
    "lat": "Breitengrad",
    "lon": "Längengrad",
    "is_exact_location": "Exakte Position",
    "ringing_ring_scheme": "Beringungs-Schema",
    "ringing_species": "Art (Beringung)",
    "ringing_date": "Beringungsdatum",
    "ringing_place": "Beringungsort",
    "ringing_lat": "Breitengrad (Beringung)",
    "ringing_lon": "Längengrad (Beringung)",
    "ringing_ringer": "Beringer",
    "ringing_sex": "Geschlecht (Beringung)",
    "ringing_age": "Alter (Beringung)",
    "ringing_status": "Status (Beringung)",
}


reverse_mapping = {v: k for k, v in mapping.items()}
